kind: pipeline
type: docker
name: default

platform:
  os: windows
  arch: amd64
  version: 1903
  
steps:
- name: build
  commands:
  - utopia_bot.exe --pk 02EC6D2E76D48AC3357B6D0D7F5E6436C5513DF38DF8D2C9EE31341185D0501D
